CREATE TABLE PIEZAS
(
ID_PIEZA NUMBER CONSTRAINT PK_PIEZAS PRIMARY KEY,
COD_PIEZA CHAR(3) NOT NULL CONSTRAINT SK_PIEZAS_1 UNIQUE,
DESCRIP_PIEZA VARCHAR (20),
COLOR VARCHAR (15),
PESO NUMBER (5,2)
)

CREATE TABLE PROVEEDORES
(
ID_PROVEEDOR NUMBER CONSTRAINT PK_PROVEEDORES PRIMARY KEY,
COD_PROVEEDOR CHAR (2) NOT NULL CONSTRAINT SK_PROVEEDORES_1 UNIQUE,
NOMBRE_PROVEEDOR VARCHAR(25),
CIUDAD_PROVEEDOR VARCHAR (25),
FECHA_NAC_PROVEEDOR DATE
)

CREATE TABLE SUMINISTROS
(
ID_SUMINISTRO NUMBER CONSTRAINT PK_SUMINISTROS PRIMARY KEY,
REF_SUMINISTRO CHAR (4) NOT NULL CONSTRAINT SK_SUMINISTROS_1 UNIQUE,
ID_PIEZA NUMBER NOT NULL,
CONSTRAINT FK_SUMINISTROS_1 FOREIGN KEY (ID_PIEZA) REFERENCES PIEZAS (ID_PIEZA),
UNIDADES NUMBER (3),
ID_PROVEEDOR NUMBER NOT NULL,
CONSTRAINT FK_SUMINISTROS_2 FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (ID_PROVEEDOR)
)

CREATE SEQUENCE SEC_PIEZAS
CREATE SEQUENCE SEC_PROVEEDORES
CREATE SEQUENCE SEC_SUMINISTROS

INSERT INTO PIEZAS VALUES (SEC_PIEZAS.NEXTVAL, '101','TUERCA','NEGRO',3);
INSERT INTO PIEZAS VALUES (SEC_PIEZAS.NEXTVAL, '102','PISTÓN','AZUL',9);
INSERT INTO PIEZAS VALUES (SEC_PIEZAS.NEXTVAL, '103','PLETINA','ROJO',11);
INSERT INTO PIEZAS VALUES (SEC_PIEZAS.NEXTVAL, '106','TUERCA','NARANJA',21);
INSERT INTO PIEZAS VALUES (SEC_PIEZAS.NEXTVAL,'105','PISTÓN','ROJO',13);

INSERT INTO PROVEEDORES VALUES (SEC_PROVEEDORES.NEXTVAL,'S1','PÉREZ S.A.','MADRID','1/12/2006');
INSERT INTO PROVEEDORES VALUES (SEC_PROVEEDORES.NEXTVAL,'S2','SÁEZ S.L.','ZARAGOZA','1/1/2000');
INSERT INTO PROVEEDORES VALUES (SEC_PROVEEDORES.NEXTVAL,'S3','METAL S.A.','BARCELONA','1/1/1995');
INSERT INTO PROVEEDORES VALUES (SEC_PROVEEDORES.NEXTVAL,'S4','TECNOSA','BILBAO','1/1/1985');

INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R001',22,9,7);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R002',24,4,7);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R003',25,2,7);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R004',26,3,7);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R005',22,3,8);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R006',24,8,8);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R007',27,11,8);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R008',26,9,8);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R009',22,7,9);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R010',24,11,9);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R011',25,7,10);
INSERT INTO SUMINISTROS VALUES (SEC_SUMINISTROS.NEXTVAL,'R012',26,13,10);