DROP INDEX SK_CLIE1
DROP INDEX SK_CLIE2
DROP INDEX SK_CLIE3

DROP INDEX SK_TITU1

ALTER TABLE TITULARES DROP CONSTRAINTS fk_titu1
ALTER TABLE TITULARES DROP CONSTRAINTS pk_titu
DROP TABLE CLIENTES CASCADE CONSTRAINTS

DROP TABLE TITULARES
DROP TABLE CUENTAS
DROP TABLE SUCURSALES
DROP TABLE CLIENTES